apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk-cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk-cars
  template:
    metadata:
      labels:
        app: nk-cars
    spec:
      containers:
      - name: nk-cars
        image: nk-cars-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
